name: PHP Linting (Pint)
on: [push]
jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
      - name: Run Laravel pint
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
